version: "3.8"
services:
    database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=admin_db
            - POSTGRES_PASSWORD=admin_db
            - POSTGRES_DB=db
        ports: 
            - "54320:5432"
        restart: always
        volumes: 
            - ./postgres-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment: 
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        ports:
            - '5050:80'
        restart: always
        volumes: 
            - pgadmin-data:/var/lib/pgadmin
volumes:
    database-data:
    pgadmin-data:
