export enum PlayerPosition {
    POINT_GUARD = "POINT_GUARD",
    SHOOTING_GUARD = "SHOOTING_GUARD",
    POWER_FORWARD = "POWER_FORWARD",
    SMALL_FORWARD = "SMALL_FORWARD",
    CENTER = "CENTER",
    GUARD = "GUARD",
    POINT_FORWARD = "POINT_FORWARD",
    FORWARD = "FORWARD",
    SWINGMAN = "SWINGMAN",
}
